### PR TITLE
gh: update default bug report template

### PR DESCRIPTION
**Pull request by mythi**
Move the org wide bug report template to use Github's issue form.

### CODE REVIEW

**Review by fitzthum — APPROVED** [review]
LGTM and the preview seems to look right

**Review by bpradipt — APPROVED** [review]
/lgtm

**Comment by mythi** [comment]
Added: "failing command" to the logs sections because I've seen it missing in few relevant places

**Comment by fitzthum** [comment]
[Seems to work](https://github.com/confidential-containers/guest-components/issues/new?assignees=&labels=bug&projects=&template=01-bug-report.yml)

**Pull request merged**
