### PR TITLE
Add CNCF Code of Conduct

### PR DESCRIPTION
**Pull request by dcmiddle**
Fixes https://github.com/confidential-containers/community/issues/11

### CODE REVIEW

**Review by sameo — COMMENTED** [review]
Thanks for opening that PR @dcmiddle. Given that we already have that CoC at https://github.com/confidential-containers/community/blob/main/CODE_OF_CONDUCT.md, and that the CNCF issue explicitly asks for referencing from the project's README, could we instead add a link from this repo's `README.md` to the community CoC instead?

**Comment by magowan** [comment]
I guess I am not totally clear on "Then we have a central place for all repos to pick the CoC file."
Happy to be educated on what Github offers to do this through using the .github project?

Individual repo readmes aside I was thinking we should update the profile/README, then anyone who lands on https://github.com/confidential-containers finds an obvious link to the CNCF code of conduct?

**Comment by peterzcst** [comment]
Please specify if individual repo needs including a reference to CNCF CoC

**Comment by dcmiddle** [comment]
> Please specify if individual repo needs including a reference to CNCF CoC

It doesn't hurt to add the CoC file from this PR (same as located in the community repo). This PR will make it appear at each repo (not in file form but in the info to the upper right of each page).

**Comment by dcmiddle** [comment]
@sameo @magowan @fitzthum please [re]review.

**Review by fitzthum — COMMENTED** [review]
I took a look at some of the other CNCF project githubs. It seems like most projects use a separate `CODE_OF_CONDUCT.md` file which points to the CNCF code of conduct. I only see the code of conduct specified in the main readme when there isn't any separate `CODE_OF_CONDUCT.md` file. Since we have `CODE_OF_CONDUCT.md` in all(ish) of our repos, I'm not sure that we need to add this. 

Our situation is slightly different because we use the organization profile as the landing page for the project. Technically we have no code of conduct stuff in the profile repo, but I don't think this is a big deal, especially given that we pin the community repo.

**Comment by dcmiddle** [comment]
@sameo @fitzthum rebased

**Review by sameo — APPROVED** [review]

**Pull request merged**
